### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by clarakosi**

### CODE REVIEW

**Comment by jdforrester** [comment]
Ouch, we should migrate this repo to GH Actions (and switch up from testing on node 4 and 6, both EOL).

**Comment by clarakosi** [comment]
@jdforrester I agree. I was thinking maybe node 8 and 10?

**Comment by jdforrester** [comment]
Done for 8/10/12 (our normal mix).

**Comment by clarakosi** [comment]
Nice! Thanks

**Review by Pchelolo — APPROVED** [review]

**Comment by Pchelolo** [comment]
waiting for the checks

**Pull request merged**
